---
driver:
  name: vagrant
  synced_folders:
    - ["test/assets/packages", "/mnt/kitchen/packages"]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[objectivefs::default]
      - recipe[ofs_mount_test::mount]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      objectivefs:
        package:
          provider: "dpkg_package"
          source: "/mnt/kitchen/packages/objectivefs_5.2_amd64.deb"
