name 'objectivefs'
maintainer 'Michael Gutteridge'
maintainer_email 'mrg@fredhutch.org'
license 'MIT'
description 'Cookbook for ObjectiveFS'
long_description 'Installs/Configures objectivefs'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
supports 'ubuntu'
issues_url 'https://github.com/fredhutch/objectivefs/issues'
source_url 'https://github.com/fredhutch/objectivefs'
