name 'ofs_mount_test'
maintainer 'Michael Gutteridge'
maintainer_email 'mrg@fredhutch.org'
license 'Apache 2.0'
description 'runs an ofs mount'
long_description 'Test ofs_mount resource functions'
version '0.0.1'
supports 'ubuntu'
depends 'objectivefs'
